language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

sudo: false

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source
  - composer require satooshi/php-coveralls:~0.6@stable

before_script:
  - mkdir -p build/logs

script:
  - composer test

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'